### ISSUE TITLE
QL query is now failing

### ISSUE THREAD

**Issue by kaohlive** [andysmithfal/polestar.js#3]
I now get the responses:
message: 'Cannot query field "getOdometerData" on type "Query". Did you mean "getDocumentMetadata"?',
          extensions: { code: 'GRAPHQL_VALIDATION_FAILED', exception: [Object] }

 message: 'Cannot query field "getBatteryData" on type "Query".',
          extensions: { code: 'GRAPHQL_VALIDATION_FAILED', exception: [Object] }

So it looks like this nice way of interacting with the Polestar is now broken already :(

**Comment by andysmithfal** [comment]
Looks like Polestar changed the endpoint today. Should be fixed in latest commit #e4fe1e7

**Comment by kaohlive** [comment]
Excellent, tested and it works again now.
