### ISSUE TITLE
Feature request: charge limit

### ISSUE THREAD

**Issue by kaohlive** [andysmithfal/polestar.js#4]
Since today the apps now support changing the charge limit.
Can you see if the api now supports this also? If so can we expect an update to retrieve/update the charge limit?

**Comment by andysmithfal** [comment]
Afraid this would require reverse engineering the mobile app. As far as I'm aware nobody has managed to do this yet. This library uses the API available via the website, which can pull stats from the car but is entirely read-only operations. 

Essentially, if you can do it on the website, I should be able to do it with this library.
