### ISSUE TITLE
Polestar API changed

### ISSUE THREAD

**Issue by bausi2k** [andysmithfal/polestar.js#5]
The API change and therefore the access to the service is not possible anymore.

see also https://github.com/pypolestar/polestar_api/issues/197

**Comment by kaohlive** [comment]
From that link by bausi2k it seems to be the clientid that changed into "l3oopkc_10"

And a piece of extra code to handle an accept to terms and conditions:

        uid = result.next_request.url.params.get("uid")

        # handle missing code (e.g., accepting terms and conditions)
        if code is None and uid:
            _LOGGER.debug("Code missing; submit confirmation for uid=%s and retry", uid)
            data = {"pf.submit": True, "subject": uid}
            result = await self.client_session.post(
                urljoin(
                    OIDC_PROVIDER_BASE_URL,
                    f"/as/{resumePath}/resume/as/authorization.ping",
                ),
                data=data,
            )
            url = result.url
            code = result.next_request.url.params.get("code")

**Comment by andysmithfal** [comment]
Half way through fixing this, should have some time later to finish it and push out an update

**Comment by kaohlive** [comment]
If I can help out somewhere let me know. Not sure how far you got, but if you need someone to test and complete it I can help out

**Comment by andysmithfal** [comment]
Sorry for the delay - should be fixed in latest update. I'm not entirely sure if this will work without the user first logging in to Polestar.com and manually accepting the T&Cs, but as I'd already done that on my account i was unable to test this.

**Comment by kaohlive** [comment]
Worked for my test without any visit to the polestar site. But also can not remember if I did some time ago to accept any t&c in the past though. Thanks

**Comment by bausi2k** [comment]
worked for me as well - thx a lot!
