### ISSUE TITLE
Oops they did it again…

### ISSUE THREAD

**Issue by bausi2k** [andysmithfal/polestar.js#6]
Sorry to bother, but the changed the api again.

tried to quickly change it myself didn't work :-(

Hint: https://github.com/CONSULitAS/Polestar_2_MQTT_Docker/pull/10/files

**Comment by andysmithfal** [comment]
Fixed, I've had to disable some of the more stringent token validity checking until I work out a new endpoint, but the library should work again now

**Comment by bausi2k** [comment]
thx a lot
