### ISSUE TITLE
Login is failing for users

### ISSUE THREAD

**Issue by kaohlive** [andysmithfal/polestar.js#7]
Since yesterday I can no longer use the login method it seems.
I am getting the error
TypeError: Cannot read properties of null (reading 'access_token')
    at Polestar.#getApiToken (/node_modules/@andysmithfal/polestar.js/polestar.js:248:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Polestar.login (/node_modules/@andysmithfal/polestar.js/polestar.js:31:22)

Not sure what changed. Anyone else sufforing from this problem?

**Comment by andysmithfal** [comment]
Looks like they've changed it again - I'd not noticed as the version I'm running is still refreshing access tokens ok, but it looks like new logins are failing. I'll take a look when I get a moment

**Comment by kaohlive** [comment]
I debugged a bit more:
{"errors":[{"message":"An internal error has occured.","path":["getAuthToken"],"extensions":{"code":"BAD_USER_INPUT","exception":{"stacktrace":["UserInputError: An internal error has occured.","    at jZi (/var/task/src/functions/auth/handler.js:1381:2697051)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async KZi (/var/task/src/functions/auth/handler.js:1381:2697884)","    at async getAuthToken (/var/task/src/functions/auth/handler.js:1381:2724149)"],"message":"An internal error has occured.","locations":[{"line":1,"column":44}],"path":["getAuthToken"]},"serviceName":"auth"}}],"data":{"getAuthToken":null}}

**Comment by kaohlive** [comment]
Ineresting read in this issue for the HA py integration, there are also people that starting having issues again since 3 days.
There is also mention of a v2 api?
https://github.com/pypolestar/polestar_api/issues/190

**Comment by andysmithfal** [comment]
Fixed in 1.2.0

**Comment by kaohlive** [comment]
great seems to work perfectly again :)
