### ISSUE TITLE
Enhancment: Health data

### ISSUE THREAD

**Issue by kaohlive** [andysmithfal/polestar.js#8]
It seems there is now API support for car health like maintenance etc.
https://github.com/pypolestar/polestar_api/issues/183

In this post there is a screenshot with values the P3 (so also the api now supports)
I dont have a P3, would those expose automatically for example?
https://github.com/pypolestar/polestar_api/issues/255

**Comment by andysmithfal** [comment]
Added in 1.3.0, I also don't have a PS3 but presumably the PS3/4 would return some additional info for that method call. Would be interested to know how well this library works on those cars and what extra info is returned.

**Comment by kaohlive** [comment]
Added support in my Homey app, now I only expose the service status. I asked for P3 owners to submite logs to see if there is more available

**Comment by andysmithfal** [comment]
I'm just glad I'll know if my engine coolant or oil gets low 😂

**Comment by kaohlive** [comment]
😂😂Yeah noticed those also

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
