### ISSUE TITLE
Another signin issue due to API change 

### ISSUE THREAD

**Issue by kaohlive** [andysmithfal/polestar.js#9]
There seems to be another API change

There seems to be a solution already

1. Initialize authentication The initial call to https://polestarid.eu.polestar.com/as/authorization.oauth2 should now include PKCE related properties:

{
  'response_type' => 'code',
  'client_id' => 'l3oopkc_10',
  'redirect_uri' => 'https://www.polestar.com/sign-in-callback',
  'state' => '<uuid>', // Polestar will return this with the code but value can be ignored
  'code_challenge' => '**sha256-hash-of-code-verifier**',
  'scope' => 'openid profile email customer:attributes',
  'code_challenge_method' => 'S256'
}
2. Exchange code for access token POST to https://polestarid.eu.polestar.com/as/token.oauth2

{
  'grant_type' => 'authorization_code',
  'code' => 'code-returned-by-polestar',
  'code_verifier' => '**your-code-verifier**',
  'client_id' => 'l3oopkc_10',
  'redirect_uri' => 'https://www.polestar.com/sign-in-callback'
}
https://www.oauth.com/oauth2-servers/pkce/authorization-request/

**Comment by kaohlive** [comment]
I tried to path it myself but your code seems to work with other endpoints.

**Comment by andysmithfal** [comment]
Fixed in 1.4.0, hopefully they'll leave it alone for a while!

**Comment by kaohlive** [comment]
Excellent work again, tested it and confirm it is working again
